routes/web.php
<?php

use App\Http\Controllers\EmployeeController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
Route::get('/', function () {
    return redirect('dashboard');
});

Route::resource('employee', EmployeeController::class);
Route::get('dashboard', [EmployeeController::class, 'index'])->name('dashboard');

app/Livewire/EmployeeCreate.php
<?php

namespace App\Livewire;

use App\Models\Employee;
use Illuminate\Support\Collection;
use Livewire\Component;
use Livewire\Attributes\On;

class EmployeeCreate extends Component
{
    public $useFaker = false;
    public Employee $model;
    public Employee $placeholders;


    public function mount()
    {
        $this->placeholders = Employee::factory()->make();
        $this->model = $this->useFaker ? $this->placeholders : Employee::new();
    }

    #[On('employee-edit')]
    public function edit($id)
    {
        $this->model = Employee::findOrFail($id);
    }

    public function fillFake() {
        $this->model = $this->placeholders;
    }

    public function save()
    {
        if ($this->model->id ?? false) {
            $this->model->save();
            $this->dispatch('employee-created', ['id' => $this->model->id]);
        } else {
            $this->model->save();
        }

        return $this->redirect('/dashboard');
    }

    public function render()
    {
        return view('livewire.employee-form');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

resources/views/pages/dashboard/dashboard.blade.php
<x-app-layout>
    <div class="px-4 sm:px-6 lg:px-8 py-8 w-full max-w-9xl mx-auto"
        x-data="{modalFormOpen: false}"
         x-on:employee-edit="console.log('edit');modalFormOpen = true;"
    >
        
        <!-- Welcome banner -->
        <x-dashboard.welcome-banner />

        <!-- Dashboard actions -->
        <div class="sm:flex sm:justify-between sm:items-center mb-8">

            <!-- Left: Avatars -->
            <x-dashboard.dashboard-avatars />

            <!-- Right: Actions -->
            <div class="grid grid-flow-col sm:auto-cols-max justify-start sm:justify-end gap-2">

                <!-- Filter button -->
                <x-dropdown-filter align="right" />

                <!-- Datepicker built with flatpickr -->
{{--                <x-datepicker />--}}

                <!-- Add view button -->
                <button class="btn bg-indigo-500 hover:bg-indigo-600 text-white">
                    <svg class="w-4 h-4 fill-current opacity-50 shrink-0" viewBox="0 0 16 16">
                        <path d="M15 7H9V1c0-.6-.4-1-1-1S7 .4 7 1v6H1c-.6 0-1 .4-1 1s.4 1 1 1h6v6c0 .6.4 1 1 1s1-.4 1-1V9h6c.6 0 1-.4 1-1s-.4-1-1-1z" />
                    </svg>
                    <span class="hidden xs:block ml-2" x-on:click="modalFormOpen=true;">Add Employee</span>
                </button>
                
            </div>

        </div>
        
        <!-- Cards -->
        <div class="grid grid-cols-12 gap-6">
                @livewire('employee-table')
                @livewire('employee-create')
                @livewire('employee-chart')
        </div>

    </div>
</x-app-layout>